name: My first project

on:
  push: 
      branches: main

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Save the Welcome Message
        run: |
          echo "Welcome to GitHub Actions!" > welcome.txt
          
      - name: Display Welcome Message
        run: |
              cat welcome.txt
            
      
