name: My first project

on:
  push: 
      branches: main

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Welcome Message
        run: |
          echo "Welcome to GitHub Actions!"
            
      
